development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: catan
  pool: 5

  #any more code in the production configuration than this and herokue won't migrate


  #---------------Uncomment Below Code if Postgresql DB desired for testing and development------#

  # development:
#   adapter: postgresql
#   encoding: unicode
#   database: catan_development
#   pool: 5
#   username:
#   password:
#   timeout: 5000
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: catan_test
#   pool: 5
#   username:
#   password:
#   timeout: 5000

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: catan
#   pool: 5
#   username:
#   password:
#   timeout: 5000